<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitReportReporter -->
<testsuite hostname="hadoop04" name="javateam2.LRUMapTest" tests="15" failures="0" timestamp="14 Dec 2011 07:22:04 GMT" time="3.017" errors="1">
  <testcase name="testSize" time="0.000" classname="javateam2.LRUMapTest"/>
  <testcase name="testDiscardWithTime" time="1.001" classname="javateam2.LRUMapTest"/>
  <testcase name="testResize2" time="0.000" classname="javateam2.LRUMapTest"/>
  <testcase name="testGetNull2" time="0.000" classname="javateam2.LRUMapTest"/>
  <testcase name="testPut" time="0.001" classname="javateam2.LRUMapTest"/>
  <testcase name="testResize3" time="0.000" classname="javateam2.LRUMapTest"/>
  <testcase name="testConstructorType1" time="0.000" classname="javateam2.LRUMapTest"/>
  <testcase name="testConstructorType2" time="0.001" classname="javateam2.LRUMapTest"/>
  <testcase name="testSize3" time="0.000" classname="javateam2.LRUMapTest"/>
  <testcase name="testPutSameKey" time="0.001" classname="javateam2.LRUMapTest"/>
  <testcase name="testResize" time="0.001" classname="javateam2.LRUMapTest"/>
  <testcase name="testDiscardWithTime2" time="2.001" classname="javateam2.LRUMapTest">
    <error type="java.lang.AssertionError" message="expected:&lt;null&gt; but was:&lt;2nd&gt;">
      <![CDATA[java.lang.AssertionError: expected:<null> but was:<2nd>
	at org.testng.AssertJUnit.assertEquals(AssertJUnit.java:101)
	at org.testng.AssertJUnit.assertEquals(AssertJUnit.java:108)
	at javateam2.LRUMapTest.testDiscardWithTime2(LRUMapTest.java:150)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:39)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:25)
	at java.lang.reflect.Method.invoke(Method.java:597)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:80)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:676)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:845)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1169)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:125)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:109)
	at org.testng.TestRunner.runWorkers(TestRunner.java:1182)
	at org.testng.TestRunner.privateRun(TestRunner.java:761)
	at org.testng.TestRunner.run(TestRunner.java:612)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:335)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:330)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:292)
	at org.testng.SuiteRunner.run(SuiteRunner.java:241)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1169)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1094)
	at org.testng.TestNG.run(TestNG.java:1006)
	at org.testng.remote.RemoteTestNG.run(RemoteTestNG.java:107)
	at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:199)
	at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:170)
]]>
    </error>
  </testcase>
  <testcase name="testGetNull" time="0.001" classname="javateam2.LRUMapTest"/>
  <testcase name="testConstructorSize" time="0.000" classname="javateam2.LRUMapTest"/>
  <testcase name="testConstructorException" time="0.010" classname="javateam2.LRUMapTest"/>
</testsuite>
